select
STATUS,
NOTICENUM,
PURCHUNIT,
ENDCUSTMER,
DEVPERIOD,
ORITEMNUM,
DELIWAREHOUSE,
TRANSWAY,
COMMODITYNAME,
QUALITY,
MATERIAL,
STANDARD,
CREATTIME,
ALTERTIME,
DETAILADDRESS,
CANSENDNUMBER,
CANSENDWEIGHT
from
db_inter.bclp_can_be_send_amount
where
STATUS != 'D'
and TRANSWAY like '汽运快运%%'
and DELIWARE in (' -','U6-黄岛库(外库)')
and DETAILADDRESS like '山东%%'
ORDER BY ORITEMNUM